onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider U_qsgmii_test
add wave -noupdate -divider ipsxb_qsgmii_dut_top_tb
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_pkg_gen_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p0_crc_ok_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p1_crc_ok_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p2_crc_ok_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p3_crc_ok_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p0_rcving_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p1_rcving_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p2_rcving_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p3_rcving_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_pkg_gen_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p0_crc_ok_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p1_crc_ok_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p2_crc_ok_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p3_crc_ok_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p0_rcving_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p1_rcving_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p2_rcving_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p3_rcving_cnt
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p0_gmii_dv
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p1_gmii_dv
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p2_gmii_dv
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p3_gmii_dv
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p0_gmii_dv
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p1_gmii_dv
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p2_gmii_dv
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p3_gmii_dv
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p0_clk_en_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p1_clk_en_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p2_clk_en_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p3_clk_en_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p0_clk_en_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p1_clk_en_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p2_clk_en_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p3_clk_en_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p0_gmii_dv_ff
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p1_gmii_dv_ff
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p2_gmii_dv_ff
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p3_gmii_dv_ff
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p0_gmii_dv_ff
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p1_gmii_dv_ff
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p2_gmii_dv_ff
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p3_gmii_dv_ff
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p0_rcving_data_pulse_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p1_rcving_data_pulse_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p2_rcving_data_pulse_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p3_rcving_data_pulse_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p0_rcving_data_pulse_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p1_rcving_data_pulse_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p2_rcving_data_pulse_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p3_rcving_data_pulse_d1
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_check_valid
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_check_valid
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p0_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p1_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p2_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_p3_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p0_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p1_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p2_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_p3_rx_ok
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_check_result
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_check_result
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_lh_signal_loss
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_ll_cdr_align
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_ll_tx_pll_lock
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u1_ll_lsm_synced
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_lh_signal_loss
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_ll_cdr_align
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_ll_tx_pll_lock
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/u2_ll_lsm_synced
add wave -noupdate -group tb_check /ipsxb_qsgmii_dut_top_tb/chk_rst_n
add wave -noupdate -divider U1_ipsxb_qsgmii_top
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_status_vector
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_pin_cfg_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_phy_link
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_phy_duplex
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_phy_speed
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_unidir_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_an_restart
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_an_enable
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_loopback
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_sgmii_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_tx_clken
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_tx_rstn_sync
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_rx_dv
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_rx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_receiving
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_txd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_tx_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_tx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_transmitting
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_status_vector
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_pin_cfg_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_phy_link
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_phy_duplex
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_phy_speed
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_unidir_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_an_restart
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_an_enable
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_loopback
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_sgmii_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_tx_clken
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_tx_rstn_sync
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_rx_dv
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_rx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_receiving
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_txd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_tx_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_tx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_transmitting
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_status_vector
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_pin_cfg_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_phy_link
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_phy_duplex
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_phy_speed
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_unidir_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_an_restart
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_an_enable
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_loopback
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_sgmii_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_tx_clken
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_tx_rstn_sync
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_rx_dv
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_rx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_receiving
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_txd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_tx_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_tx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_transmitting
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_status_vector
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_pin_cfg_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_phy_link
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_phy_duplex
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_phy_speed
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_unidir_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_an_restart
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_an_enable
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_loopback
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_sgmii_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_tx_clken
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_tx_rstn_sync
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_rx_dv
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_rx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_receiving
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_txd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_tx_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_tx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_transmitting
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/P_L0TXN
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/P_L0TXP
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/P_L0RXN
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/P_L0RXP
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/P_REFCKN
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/P_REFCKP
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_signal_loss
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_cdr_align
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_tx_pll_lock
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_lsm_synced
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/hsst_ch_ready
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/external_rstn
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/free_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_AN_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_AN_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_RS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_RS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_TS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_TS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_xmit
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p0_rx_unitdata_indicate
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_AN_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_AN_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_RS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_RS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_TS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_TS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_xmit
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p1_rx_unitdata_indicate
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_AN_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_AN_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_RS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_RS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_TS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_TS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_xmit
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p2_rx_unitdata_indicate
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_AN_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_AN_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_RS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_RS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_TS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_TS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_xmit
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/p3_rx_unitdata_indicate
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_rx_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_rxk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_rdispdec_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_txk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_tx_dispctrl
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_tx_dispsel
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U1_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_txd
add wave -noupdate -divider U2_ipsxb_qsgmii_dut
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_status_vector
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_pin_cfg_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_phy_link
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_phy_duplex
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_phy_speed
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_unidir_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_an_restart
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_an_enable
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_loopback
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_sgmii_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_tx_clken
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_tx_rstn_sync
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_rx_dv
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_rx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_receiving
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_txd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_tx_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_gmii_tx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_transmitting
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_status_vector
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_pin_cfg_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_phy_link
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_phy_duplex
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_phy_speed
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_unidir_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_an_restart
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_an_enable
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_loopback
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_sgmii_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_tx_clken
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_tx_rstn_sync
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_rx_dv
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_rx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_receiving
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_txd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_tx_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_gmii_tx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_transmitting
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_status_vector
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_pin_cfg_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_phy_link
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_phy_duplex
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_phy_speed
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_unidir_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_an_restart
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_an_enable
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_loopback
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_sgmii_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_tx_clken
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_tx_rstn_sync
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_rx_dv
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_rx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_receiving
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_txd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_tx_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_gmii_tx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_transmitting
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_status_vector
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_pin_cfg_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_phy_link
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_phy_duplex
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_phy_speed
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_unidir_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_an_restart
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_an_enable
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_loopback
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_sgmii_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_tx_clken
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_tx_rstn_sync
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_rx_dv
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_rx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_receiving
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_txd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_tx_en
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_gmii_tx_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_transmitting
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/P_L0TXN
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/P_L0TXP
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/P_L0RXN
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/P_L0RXP
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/P_REFCKN
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/P_REFCKP
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_signal_loss
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_cdr_align
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_tx_pll_lock
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_lsm_synced
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/hsst_ch_ready
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/external_rstn
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/free_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/qsgmii_tx_rstn
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/qsgmii_rx_rstn
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_AN_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_AN_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_RS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_RS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_TS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_TS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_xmit
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p0_rx_unitdata_indicate
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_AN_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_AN_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_RS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_RS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_TS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_TS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_xmit
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p1_rx_unitdata_indicate
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_AN_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_AN_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_RS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_RS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_TS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_TS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_xmit
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p2_rx_unitdata_indicate
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_AN_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_AN_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_RS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_RS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_TS_CS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_TS_NS
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_xmit
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/p3_rx_unitdata_indicate
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_rx_clk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_rxk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_rdispdec_er
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_rxd
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_txk
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_tx_dispctrl
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_tx_dispsel
add wave -noupdate -radix hexadecimal /ipsxb_qsgmii_dut_top_tb/U_inst_tb/U2_ipsxb_qsgmii_dut/U_qsgmii_test/l0_pcs_txd
WaveRestoreCursors {{Cursor 1} {364537142640 fs} 0}
configure wave -namecolwidth 207
configure wave -valuecolwidth 39
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {342723786301 fs} {365732648662 fs}
